### ISSUE TITLE
Remark GFM plugin issues

### ISSUE THREAD

**Issue by swsvindland** [remarkjs/react-remark#76] opened 2024-03-31 17:17 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.0 && 4.0.0

### Link to runnable example

https://codesandbox.io/p/devbox/2g4wrr?file=%2Fsrc%2FApp.tsx%3A30%2C3

### Steps to reproduce

Using react-remark and remark-gfm nothing renders
i tested with remark-gemoji and that seems to work fine, so could be that plugin or im missing a setup step

### Expected behavior

Should render
Tables should work

### Actual behavior

renders nothing

### Runtime

Node v17, Node v16

### Package manager

yarn 2, pnpm

### OS

Windows, macOS

### Build and bundle tools

Create React App, Vite

**Comment by ChristianMurphy** [comment] 2024-03-31 18:22
Duplicate of https://github.com/remarkjs/react-remark/issues/41

**Closed as completed by ChristianMurphy** 2024-03-31 18:22 UTC
Labels: 👯 no/duplicate
