### ISSUE TITLE
Type conflict / Update to unified v10

### ISSUE THREAD

**Issue by reckter** [remarkjs/react-remark#62] opened 2023-08-03 13:14 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-remark@2.1.0

### Steps to reproduce

I've tried to update `@types/unist` to v3 from v2, but that causes a type error when trying to give Remark a list of plugins:

```
Type '() => (tree: Node) => Node' is not assignable to type 'Pluggable<any[], Settings>'.
  Type '() => (tree: Node) => Node' is not assignable to type 'Plugin<any[], Settings>'.
    Type '(tree: Node) => Node' is not assignable to type 'void | Transformer'.
      Type '(tree: Node) => Node' is not assignable to type 'Transformer'.
        Type 'Node' is not assignable to type 'void | Error | Node<Data> | Promise<Node<Data>> | Promise<void>'.
          Type 'Node' is not assignable to type 'Node<Data>'.
            Types of property 'data' are incompatible.
              Type 'import("[...]/node_modules/.pnpm/@types+unist@3.0.0/node_modules/@types/unist/index").Data | undefined' is not assignable to type 'import("[...]/node_modules/.pnpm/@types+unist@2.0.6/node_modules/@types/unist/index").Data | undefined'.
                Type 'import("[...]/node_modules/.pnpm/@types+unist@3.0.0/node_modules/@types/unist/index").Data' is not assignable to type 'import("[...]/node_modules/.pnpm/@types+unist@2.0.6/node_modules/@types/unist/index").Data'.
                  Index signature for type 'string' is missing in type 'Data'.

178       remarkPlugins={[remarkEntityLinks]}
                          ~~~~~~~~~~~~~~~~~
``` 

This seems to be, because `react-remark` is still using `unified@9.x`, which intern is still depending on `@types/unist@2.x`.

### Expected behavior

The types work with the most up to date versions of `@types/unist`

### Actual behavior

There is a type conflict in the `Node` type between `@types/unist@2` and `@types/unist@3`

**Comment by ChristianMurphy** [comment] 2023-08-03 13:58
Thanks for reaching out @reckter! 👋 

This is a duplicate of #50

The next major release will support unified 11 and remark 15 (currently in the process of being released) based off the work in https://github.com/remarkjs/react-remark/pull/39
As noted in https://github.com/remarkjs/react-remark/issues/54 there are a few higher priority releases that need attention before I'll finish this.
If you are interested feel free to work on any of the checklist of planned changes in https://github.com/remarkjs/react-remark/pull/39 to help accelerate that time-line.

**Closed as not planned by ChristianMurphy** 2023-08-03 13:58 UTC
Labels: 👯 no/duplicate
